## Install and import the needed library
Pandas is needed to manipulate, analyze, and clean structured data.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2025.3)
Requirement already satisfied: pytz>=2020.1 in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/Saruttakan/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

In [2]:
import pandas as pd

## Download survey_data.csv and store it to df_original

In [3]:
df_original = pd.read_csv('survey_data.csv')

In [4]:
df_original.shape

(65437, 114)

In [5]:
pd.set_option('display.max_columns',None) #to see all the columns of the dataset
df_original.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

## Filter columns to only relavant columns for analysis

In [6]:
#select the columns that we want for an analysis
relavant_columns = ['ResponseId','Age','Country','EdLevel',
                    'LanguageHaveWorkedWith','LanguageWantToWorkWith',
                    'DatabaseHaveWorkedWith','DatabaseWantToWorkWith',
                    'PlatformHaveWorkedWith','PlatformWantToWorkWith',
                    'WebframeHaveWorkedWith','WebframeWantToWorkWith']

df = df_original[relavant_columns].copy()

Check the size (dimensions) of the dataset: (rows,columns)

In [7]:
df.shape

(65437, 12)

See the first 5 rows of the dataset

In [8]:
df.head()

,ResponseId,Age,Country,EdLevel,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith
0,1,Under 18 years old,United States of America,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,35-44 years old,United Kingdom of Great Britain and Northern I...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix
2,3,45-54 years old,United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",C#,C#,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE
3,4,18-24 years old,Canada,Some college/university study without earning ...,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React
4,5,18-24 years old,Norway,"Secondary school (e.g. American high school, G...",C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN

## Check for Duplicates

In [9]:
df['ResponseId'].duplicated().sum()

0

## Check for missing values

In [10]:
missing_values = df.isnull().sum()

In [11]:
df_missing = pd.DataFrame(missing_values.reset_index(name='missing_count'))
df_missing

                     index  missing_count
0               ResponseId              0
1                      Age              0
2                  Country           6507
3                  EdLevel           4653
4   LanguageHaveWorkedWith           5692
5   LanguageWantToWorkWith           9685
6   DatabaseHaveWorkedWith          15183
7   DatabaseWantToWorkWith          22879
8   PlatformHaveWorkedWith          23071
9   PlatformWantToWorkWith          30905
10  WebframeHaveWorkedWith          20276
11  WebframeWantToWorkWith          26902

There are many missing value in this dataset.

Let's see the percentage of missing values in each column.

In [12]:
missing_values_percent = round(df.isnull().sum() / len(df) *100,2)

In [13]:
df_missing_percent = pd.DataFrame(missing_values_percent.reset_index(name='percent'))
df_missing_percent

                     index  percent
0               ResponseId     0.00
1                      Age     0.00
2                  Country     9.94
3                  EdLevel     7.11
4   LanguageHaveWorkedWith     8.70
5   LanguageWantToWorkWith    14.80
6   DatabaseHaveWorkedWith    23.20
7   DatabaseWantToWorkWith    34.96
8   PlatformHaveWorkedWith    35.26
9   PlatformWantToWorkWith    47.23
10  WebframeHaveWorkedWith    30.99
11  WebframeWantToWorkWith    41.11

## Handling missing values

#### Country
Missing values in 'Country' likely indicate that respondents chose not to disclose their location, so they are replaced with "Unknown".

In [14]:
df['Country'] = df['Country'].fillna('Unknown')

#### EdLevel (Educational Level)
Missing values in 'EdLevel' likely indicate that respondents chose not to disclose their education level, so they are replaced with "Unknown".

In [15]:
df['EdLevel'] = df['EdLevel'].fillna('Unknown')

#### Others technology columns
Missing values likely indicate that respondents did not select any technology, so they are replaced with "None".

In [16]:
tech_cols = ['LanguageHaveWorkedWith','LanguageWantToWorkWith',
             'DatabaseHaveWorkedWith','DatabaseWantToWorkWith',
             'PlatformHaveWorkedWith','PlatformWantToWorkWith',
             'WebframeHaveWorkedWith','WebframeWantToWorkWith']

df[tech_cols] = df[tech_cols].fillna('None')

#### Check for missing values again

In [17]:
df.isnull().sum()

ResponseId                0
Age                       0
Country                   0
EdLevel                   0
LanguageHaveWorkedWith    0
LanguageWantToWorkWith    0
DatabaseHaveWorkedWith    0
DatabaseWantToWorkWith    0
PlatformHaveWorkedWith    0
PlatformWantToWorkWith    0
WebframeHaveWorkedWith    0
WebframeWantToWorkWith    0
dtype: int64

In [18]:
df.head()

,ResponseId,Age,Country,EdLevel,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith
0,1,Under 18 years old,United States of America,Primary/elementary school,None,None,None,None,None,None,None,None
1,2,35-44 years old,United Kingdom of Great Britain and Northern I...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix
2,3,45-54 years old,United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",C#,C#,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE
3,4,18-24 years old,Canada,Some college/university study without earning ...,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React
4,5,18-24 years old,Norway,"Secondary school (e.g. American high school, G...",C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,None,None,None,None

## Clean data to make it easier to analyze and visualize

#### Age

In [19]:
age_group = {'Under 18 years old': 'Under 18y',
            '18-24 years old': '18-24y',
            '25-34 years old': '25-34y',
            '35-44 years old': '35-44y',
            '45-54 years old': '45-54y',
            '55-64 years old': '55-64y',
            '65 years or older': '65y+'}

df['Age'] = df['Age'].replace(age_group)

df['Age'].value_counts()

Age
25-34y               23911
35-44y               14942
18-24y               14098
45-54y                6249
55-64y                2575
Under 18y             2568
65y+                   772
Prefer not to say      322
Name: count, dtype: int64

#### Country

In [20]:
long_name_countries = df['Country'][df['Country'].str.len() > 12].unique()
long_name_countries

array(['United States of America',
       'United Kingdom of Great Britain and Northern Ireland',
       'Iran, Islamic Republic of...', 'Czech Republic',
       'Republic of North Macedonia', 'Russian Federation',
       'United Republic of Tanzania', 'Dominican Republic',
       'Liechtenstein', 'Venezuela, Bolivarian Republic of...',
       'Republic of Korea', 'Bosnia and Herzegovina',
       'Republic of Moldova', 'United Arab Emirates',
       'Hong Kong (S.A.R.)', "Lao People's Democratic Republic",
       'Democratic Republic of the Congo', 'Syrian Arab Republic',
       "Côte d'Ivoire", 'Trinidad and Tobago',
       "Democratic People's Republic of Korea", 'Papua New Guinea',
       'Congo, Republic of the...', 'Guinea-Bissau',
       'Central African Republic', 'Equatorial Guinea',
       'Libyan Arab Jamahiriya', 'Brunei Darussalam',
       'Antigua and Barbuda', 'Saint Kitts and Nevis',
       'Micronesia, Federated States of...', 'Solomon Islands'],
      dtype=object)

In [21]:
country_map = {
    'United Kingdom of Great Britain and Northern Ireland': 'UK',
    'United States of America': 'USA',
    'Republic of North Macedonia': 'North Macedonia',
    'United Republic of Tanzania': 'Tanzania',
    'Czech Republic': 'Czechia',
    'Russian Federation': 'Russia',
    'Venezuela, Bolivarian Republic of...': 'Venezuela',
    'Hong Kong (S.A.R.)': 'Hong Kong',
    'United Arab Emirates': 'UAE',
    'Iran, Islamic Republic of...': 'Iran',
    'Democratic Republic of the Congo': 'DR Congo',
    'Republic of Korea': 'South Korea',
    'Syrian Arab Republic': 'Syria',
    'Côte d\'Ivoire': 'Ivory Coast',   # <-- escaped apostrophe
    'Republic of Moldova': 'Moldova',
    'Congo, Republic of the...': 'Republic of the Congo',
    'Brunei Darussalam': 'Brunei'
}

df['Country'] = df['Country'].replace(country_map)

df['Country'].value_counts()

Country
USA                         11095
Unknown                      6507
Germany                      4947
India                        4231
UK                           3224
                            ...
Papua New Guinea                1
Dominica                        1
Equatorial Guinea               1
Central African Republic        1
Solomon Islands                 1
Name: count, Length: 185, dtype: int64

#### EdLevel (Education Level)

In [22]:
education_map = {'Bachelor’s degree (B.A., B.S., B.Eng., etc.)': 'Bachelor’s degree',
                'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)': 'Master’s degree',
                'Some college/university study without earning a degree': 'Study wo degree',
                'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)': 'Secondary School',
                'Professional degree (JD, MD, Ph.D, Ed.D, etc.)': 'Professional degree',
                'Associate degree (A.A., A.S., etc.)': 'Associate degree',
                'Primary/elementary school': 'Primary school'}

df['EdLevel'] = df['EdLevel'].replace(education_map)

df['EdLevel'].value_counts()

EdLevel
Bachelor’s degree      24942
Master’s degree        15557
Study wo degree         7651
Secondary School        5793
Unknown                 4653
Professional degree     2970
Associate degree        1793
Primary school          1146
Something else           932
Name: count, dtype: int64

### These columns below contain multiple answers from the respondents (Multiple-Values Columns)

These columns are LanguageHaveWorkedWith, LanguageWantToWorkWith, DatabaseHaveWorkedWith, DatabaseWantToWorkWith, PlatformHaveWorkedWith, PlatformWantToWorkWith, WebframeHaveWorkedWith, and WebframeWantToWorkWith 

We need to split each of them by ;

#### Programming Language

In [23]:
df_lang = df[['ResponseId', 'Age', 'Country', 'EdLevel',
              'LanguageHaveWorkedWith', 'LanguageWantToWorkWith']].copy()

df_lang['LanguageHaveWorkedWith'] = df_lang['LanguageHaveWorkedWith'].str.split(';')
df_lang = df_lang.explode('LanguageHaveWorkedWith')
df['LanguageHaveWorkedWith'] = df['LanguageHaveWorkedWith'].str.strip()

df_lang['LanguageWantToWorkWith'] = df_lang['LanguageWantToWorkWith'].str.split(';')
df_lang = df_lang.explode('LanguageWantToWorkWith')
df_lang['LanguageWantToWorkWith'] = df_lang['LanguageWantToWorkWith'].str.strip()

In [24]:
df_lang.head()

,ResponseId,Age,Country,EdLevel,LanguageHaveWorkedWith,LanguageWantToWorkWith
0,1,Under 18y,USA,Primary school,None,None
1,2,35-44y,UK,Bachelor’s degree,Bash/Shell (all shells),Bash/Shell (all shells)
1,2,35-44y,UK,Bachelor’s degree,Bash/Shell (all shells),Go
1,2,35-44y,UK,Bachelor’s degree,Bash/Shell (all shells),HTML/CSS
1,2,35-44y,UK,Bachelor’s degree,Bash/Shell (all shells),Java

#### Database

In [25]:
df_db = df[['ResponseId','Age','Country','EdLevel',
            'DatabaseHaveWorkedWith','DatabaseWantToWorkWith']].copy()

df_db['DatabaseHaveWorkedWith'] = df_db['DatabaseHaveWorkedWith'].str.split(';')
df_db = df_db.explode('DatabaseHaveWorkedWith')
df_db['DatabaseHaveWorkedWith'] = df_db['DatabaseHaveWorkedWith'].str.strip()

df_db['DatabaseWantToWorkWith'] = df_db['DatabaseWantToWorkWith'].str.split(';')
df_db = df_db.explode('DatabaseWantToWorkWith')
df_db['DatabaseWantToWorkWith'] = df_db['DatabaseWantToWorkWith'].str.strip()

In [26]:
df_db.head()

,ResponseId,Age,Country,EdLevel,DatabaseHaveWorkedWith,DatabaseWantToWorkWith
0,1,Under 18y,USA,Primary school,None,None
1,2,35-44y,UK,Bachelor’s degree,Dynamodb,PostgreSQL
1,2,35-44y,UK,Bachelor’s degree,MongoDB,PostgreSQL
1,2,35-44y,UK,Bachelor’s degree,PostgreSQL,PostgreSQL
2,3,45-54y,UK,Master’s degree,Firebase Realtime Database,Firebase Realtime Database

#### Platform

In [27]:
df_pl = df[['ResponseId','Age','Country','EdLevel',
                  'PlatformHaveWorkedWith','PlatformWantToWorkWith']].copy()

df_pl['PlatformHaveWorkedWith'] = df_pl['PlatformHaveWorkedWith'].str.split(';')
df_pl = df_pl.explode('PlatformHaveWorkedWith')
df_pl['PlatformHaveWorkedWith'] = df_pl['PlatformHaveWorkedWith'].str.strip()

df_pl['PlatformWantToWorkWith'] = df_pl['PlatformWantToWorkWith'].str.split(';')
df_pl = df_pl.explode('PlatformWantToWorkWith')
df_pl['PlatformWantToWorkWith'] = df_pl['PlatformWantToWorkWith'].str.strip()

In [28]:
df_pl.head()

,ResponseId,Age,Country,EdLevel,PlatformHaveWorkedWith,PlatformWantToWorkWith
0,1,Under 18y,USA,Primary school,None,None
1,2,35-44y,UK,Bachelor’s degree,Amazon Web Services (AWS),Amazon Web Services (AWS)
1,2,35-44y,UK,Bachelor’s degree,Amazon Web Services (AWS),Heroku
1,2,35-44y,UK,Bachelor’s degree,Amazon Web Services (AWS),Netlify
1,2,35-44y,UK,Bachelor’s degree,Heroku,Amazon Web Services (AWS)

#### Web Frame

In [29]:
df_web = df[['ResponseId','Age','Country','EdLevel',
             'WebframeHaveWorkedWith','WebframeWantToWorkWith']].copy()

df_web['WebframeHaveWorkedWith'] = df_web['WebframeHaveWorkedWith'].str.split(';')
df_web = df_web.explode('WebframeHaveWorkedWith')
df_web['WebframeHaveWorkedWith'] = df_web['WebframeHaveWorkedWith'].str.strip()

df_web['WebframeWantToWorkWith'] = df_web['WebframeWantToWorkWith'].str.split(';')
df_web = df_web.explode('WebframeWantToWorkWith')
df_web['WebframeWantToWorkWith'] = df_web['WebframeWantToWorkWith'].str.strip()

In [30]:
df_web.head()

,ResponseId,Age,Country,EdLevel,WebframeHaveWorkedWith,WebframeWantToWorkWith
0,1,Under 18y,USA,Primary school,None,None
1,2,35-44y,UK,Bachelor’s degree,Express,Express
1,2,35-44y,UK,Bachelor’s degree,Express,Htmx
1,2,35-44y,UK,Bachelor’s degree,Express,Node.js
1,2,35-44y,UK,Bachelor’s degree,Express,React

## Check the cleaned data

In [31]:
df.head()

,ResponseId,Age,Country,EdLevel,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith
0,1,Under 18y,USA,Primary school,None,None,None,None,None,None,None,None
1,2,35-44y,UK,Bachelor’s degree,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix
2,3,45-54y,UK,Master’s degree,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE
3,4,18-24y,Canada,Study wo degree,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React
4,5,18-24y,Norway,Secondary School,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,None,None,None,None

## Export Files

In [32]:
df.to_csv('survey_data_updated.csv', index=False)
df_lang.to_csv('languages.csv', index=False)
df_db.to_csv('databases.csv', index=False)
df_pl.to_csv('platforms.csv', index=False)
df_web.to_csv('webframes.csv', index=False)

## Create Sample Datasets and Export

In [33]:
df_original_sample = df_original.sample(300, random_state=42)
df_sample = df.sample(300, random_state=42)
df_lang_sample = df_lang.sample(300, random_state=42)
df_db_sample = df_db.sample(300, random_state=42)
df_pl_sample = df_pl.sample(300, random_state=42)
df_web_sample = df_web.sample(300, random_state=42)

In [34]:
df_original_sample.to_csv('sample_survey_data.csv', index=False)
df_sample.to_csv('sample_survey_data_updated.csv', index=False)
df_lang_sample.to_csv('sample_languages.csv', index=False)
df_db_sample.to_csv('sample_databases.csv', index=False)
df_pl_sample.to_csv('sample_platforms.csv', index=False)
df_web_sample.to_csv('sample_webframes.csv', index=False)